export { default as Heading1 } from './Typography/Heading1'
export { default as Heading2 } from './Typography/Heading2'
export { default as Heading3 } from './Typography/Heading3'
export { default as Heading4 } from './Typography/Heading4'
export { default as Body1 } from './Typography/Body1'
export { default as Body2 } from './Typography/Body2'
export { default as Subtitle } from './Typography/Subtitle'
export { default as Button } from './Typography/Button'

export { default as SectionLayout } from './SectionLayout'
