export default {
  EventDetail: [
    {
      heading: 'Startup Sprint',
      subHeading: 'e-cell',
      dateTime: '7th April, 9:00PM IST',
      location: 'NIT Rourkela',
      firstContact: 'Hardik: 7424961396',
      secondContact: 'Abhisri: 7008017752',
      desc: "Are you a developer, designer, or tech enthusiast looking to showcase your skills and create something amazing in just a few hours? Then Startup Sprint is the event for you! At National Entrepreneurship Summit [NES]’s Hackathon, you'll work in teams to develop innovative solutions to real-world problems using technology. You'll have just a few hours to brainstorm ideas, design your solution, and build a working prototype. Along the way, you'll have access to mentors and experts who can help you with technical challenges, provide feedback on your ideas, and guide you through the development process. At the end of the event, you'll have the opportunity to present your solution to a panel of judges who will evaluate your work based on factors such as creativity, technical innovation, and feasibility. The winning team will receive prizes and recognition for their outstanding work",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680535621/Anmol%20Pattnayak/Posters/startup_sprint_hy3jwb.png',
      link: 'https://unstop.com/p/startup-sprint-national-e-summit-2023-nit-rourkela-660477',
    },
    {
      heading: 'Shark Tank',
      subHeading: 'e-cell',
      dateTime: '8th & 9th April, 9:00AM IST',
      location: 'NIT Rourkela',
      firstContact: 'Swarnim: 8319493047',
      secondContact: 'Harsh: 7719861972',
      desc: "Are you an aspiring entrepreneur with a great business idea? Do you want to pitch your idea to a panel of successful investors and get the funding you need to make it a reality? Then Shark Tank is the event for you! At National Entrepreneurship Summit [NES]’s Shark Tank event, you'll have the opportunity to pitch youridea to a panel of judges who have extensive experience in entrepreneurship and investing. You'll have just a few minutes to make your pitch, so you'll need to be concise, persuasive, and confident.The judges will ask you tough questions and challenge you to defend your idea, so be prepared tothink on your feet and respond to feedback. If the judges are impressed with your pitch, they mayoffer you funding on the spot or negotiate a deal with you. Even if you're not ready to pitch your own idea, Shark Tank is a great opportunity to learn from successful entrepreneurs and investors and see what it takes to succeed in the world of business.",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680535621/Anmol%20Pattnayak/Posters/shark_tank_1_lhg7kw.png',
      link: 'https://unstop.com/p/shark-tank-national-e-summit-2023-nit-rourkela-660640',
    },
    {
      heading: 'IPL Auction',
      subHeading: 'e-cell',
      dateTime: '9th April, 9:00AM IST',
      location: 'NIT Rourkela',
      firstContact: 'Hardik: 7424961396',
      secondContact: 'Abhisri: 7008017752',
      desc: "Are you a cricket fan who loves the thrill of the game and the excitement of the auction? Then IPL Auction is the event for you! At National Entrepreneurship Summit [NES]’s IPL Auction, you'll have the opportunity to bid on your favorite players and build your own dream team. You'll have a limited budget to work with, so you'll need to be strategic and make smart decisions to get the players you want. Along the way, you'll have access to expert commentary and analysis, as well as insights into the players' strengths and weaknesses. You'll also have the chance to interact with other fans and share your thoughts on the upcoming season. At the end of the event, you'll have the satisfaction of knowing that you've assembled a team that can compete with the best. So put on your thinking cap and get ready for the excitement of the IPL Auction!",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680535623/Anmol%20Pattnayak/Posters/IPL_Auction_new_alignment-100_djoxbc.jpg',
      link: 'https://unstop.com/p/ipl-auction-national-e-summit-2023-nit-rourkela-660485',
    },
    {
      heading: 'Case Crunch',
      subHeading: 'e-cell',
      dateTime: '7th April, 9:00PM IST',
      location: 'NIT Rourkela',
      firstContact: 'Lohith: 8179437716',
      secondContact: 'Rishu: 8763637518',
      desc: "Are you a business enthusiast who loves trivia and case studies? Then the Case Crunch is the event for you! At National Entrepreneur Summit [NES]’s Case Crunch, you'll compete against other students in a total of 3 rounds testing your knowledge of business, entrepreneurship, and current events.  i)Quiz: You'll need to be quick on your feet and think creatively to answer challenging questions and stay ahead of the competition. There will be questions related to business, entrepreneurship, and current events and you need to compete against other students. ii) Case Study: You will have given the specific topic and you need to make a case study of that topic. You need to analyze the topic in all aspects for better case study. iii) Presentation: After selecting in the second round you will be given the chance to showcase your case study to the team of judges. And according to the evaluation by the judges results will be declared. This event is much more interesting for one who is an entrepreneur enthusiast.",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680535620/Anmol%20Pattnayak/Posters/Case_Crunch_New_Alignment-100_wey4se.jpg',
      link: 'https://unstop.com/p/case-crunch-national-e-summit-2023-nit-rourkela-660486',
    },
    {
      heading: 'Ad-verse',
      subHeading: 'e-cell',
      dateTime: '7th April, 9:00PM IST',
      location: 'NIT Rourkela',
      firstContact: 'Lohith: 8179437716',
      secondContact: 'Rishu: 8763637518',
      desc: "Ad-Wars is an Ad making competition conducted by Matrix, The official Marketing Club of NIT Rourkela. Descent into the realm of advertising and marketing and demonstrate your ability to develop the most effective means of attracting an audience by participating in this contest. So put on your thinking hats and begin brainstorming. Unleash your imagination, showcase your marketing skills and earn exciting rewards! There will be 2 rounds: Submission Round and Marketing round. 1) Submission Round: The participating team must submit their advertisement in either carousel or video format, selecting one of the hypothetical products given and in an acceptable file format. 2) Marketing Round: The best submissions will be qualified for this round, where the organizers will be uploading these ads, on our official Instagram handle. The team has to show their expertise in social media marketing to get their advertisement rank first among all the submissions. The advertisement that has the maximum number of likes within the mentioned time frame would be declared winner of this round",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680535620/Anmol%20Pattnayak/Posters/WhatsApp_Image_2023-04-03_at_5.56.02_PM_1_j60ojq.jpg',
      link: 'https://unstop.com/p/ad-verse-national-e-summit-2023-nit-rourkela-660487',
    },
    {
      heading: 'K12',
      subHeading: 'e-cell',
      dateTime: '8th April, 9:00AM IST',
      location: 'NIT Rourkela',
      firstContact: 'Lohith: 8179437716',
      secondContact: 'Sriram: 9676703458',
      desc: "National Entrepreneur Summit [NES] has brought the opportunity for school students from 1st to 12th standards to showcase their talents for debating a certain specific topic. Now in this event students have given a certain topic and by that topic students will share their thoughts. By this there will be conflicts between how the student will approach the topic and how he thinks about that topic. So there will be a healthy debate among the students. This event is very beneficial for the students to increase their speaking skills and ability to express their thoughts to others! ",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680535620/Anmol%20Pattnayak/Posters/WhatsApp_Image_2023-04-03_at_5.56.02_PM_zw77nf.jpg',
      link: 'https://unstop.com/p/k12-national-e-summit-2023-nit-rourkela-660488',
    },
    {
      heading: 'Entrepreneurship Conclave',
      subHeading: 'e-cell',
      dateTime: '8th April, 6:00PM IST',
      location: 'NIT Rourkela',
      firstContact: 'Lohith: 8179437716',
      secondContact: 'Sriram: 9676703458',
      desc: "A platform for industry experts and entrereneurs to collaborate, exchange ideas and gain insights to foster innovation and business growth.",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680535622/Anmol%20Pattnayak/Posters/Entrepreneurship_conclave_dvl0fg.png',
      link: 'https://unstop.com/p/entrepreneurship-conclave-national-e-summit-2023-nit-rourkela-660643',
    },
    {
      heading: 'Virtual Trading',
      subHeading: 'e-cell',
      dateTime: '8th April, 6:00PM IST',
      location: 'NIT Rourkela',
      firstContact: 'Lohith: 8179437716',
      secondContact: 'Sriram: 9676703458',
      desc: "The Bear and Bulls club of NIT Rourkela presents \"Virtual Trading\'- an exciting event that simulates the stock market trading experience right at your fingertips. Join us at the National Entrepreneurship Summit 23 and take part in this thrilling virtual trading competition where you get to trade with virtual money and win real rewards.  Also this event contains Quiz rounds also and questions related to finance. Before the competition there will be the talk on ‘Option trading’! So this is the golden opportunity to invest the time to gain knowledge about finance. ",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680550464/Anmol%20Pattnayak/Posters/dummy_vco8tb.jpg',
      link: 'https://unstop.com/p/national-entrepreneurship-summit-national-e-summit-2023-nit-rourkela-659882',
    },
    {
      heading: 'Cracking the GSoC Workshop',
      subHeading: 'e-cell',
      dateTime: '8th April, 3:00PM IST',
      location: 'NIT Rourkela',
      firstContact: 'Swarnim: 8319493047',
      secondContact: 'Abhisri: 7008017752',
      desc: "Are you interested in learning new skills and techniques that can help you succeed as an entrepreneur? Then the Workshops are the events for you! At National Entrepreneur Summit [NES]’s Workshops, you'll have the opportunity to attend handson sessions that teach you practical skills in areas such as marketing, finance, product development, and more. You'll learn from experts who have real-world experience and be able to apply what you've learned to your own business ideas. The Workshops are a great way to develop your skills, meet other entrepreneurs, and gain practical insights that can help you succeed in the world of business. So roll up your sleeves and get ready to learn!",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680550464/Anmol%20Pattnayak/Posters/dummy_vco8tb.jpg',
      link: 'https://unstop.com/p/coding-workshop-by-gsoc-mentor-national-e-summit-2023-nit-rourkela-660636',
    },
    {
      heading: 'Comedy Night',
      subHeading: 'Open Mic club',
      dateTime: '7th April, 8:00PM IST',
      location: 'NIT Rourkela',
      firstContact: 'Swarnim: 8319493047',
      secondContact: 'Abhisri: 7008017752',
      desc: "This event will be done by the Open Mike Club at the SAC. In this event there will be a person called comedian who will make you laugh by his sense of humor and by telling his past stories.  “Laughter is wine for the soul”,so get ready to laugh a lot and enjoy the comedy",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680550464/Anmol%20Pattnayak/Posters/dummy_vco8tb.jpg',
      link: 'https://unstop.com/p/national-entrepreneurship-summit-national-e-summit-2023-nit-rourkela-659882',
    },
    {
      heading: 'Musical Night',
      subHeading: 'Drill n Bass',
      dateTime: '9th April, 7:00PM IST',
      location: 'NIT Rourkela',
      firstContact: 'Swarnim: 8319493047',
      secondContact: 'Abhisri: 7008017752',
      desc: "This event will be done by the Drill N Bass club of the NIT Rourkela. As its name says, there will be performances of the musicians with musical instruments with a complete music band to drive you in the journey of excitement. “Crazy nights make better memories”, so get ready for this night to level up your energy!",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680550464/Anmol%20Pattnayak/Posters/dummy_vco8tb.jpg',
      link: 'https://unstop.com/p/national-entrepreneurship-summit-national-e-summit-2023-nit-rourkela-659882',
    },
    {
      heading: 'Act',
      subHeading: 'Pantomime',
      dateTime: '8th April, 5:00PM IST',
      location: 'NIT Rourkela',
      firstContact: 'Hardik: 7424961396',
      secondContact: 'Abhisri: 7008017752',
      desc: "This is the very creative act which will be done by the Pantomime club of the NIT Rourkela. In this event a group of students will perform an act with background music behind the act. And that act with great acting and collectively performing skills will show you the real time lesson in the community. So get ready for witnessing this unique act!",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680550464/Anmol%20Pattnayak/Posters/dummy_vco8tb.jpg',
      link: 'https://unstop.com/p/national-entrepreneurship-summit-national-e-summit-2023-nit-rourkela-659882',
    },
    {
      heading: 'Highlight Sessions 1',
      subHeading: 'e-cell',
      dateTime: '7th April, 12:00PM IST',
      location: 'NIT Rourkela',
      firstContact: 'Swarnim: 8319493047',
      secondContact: 'Harsh: 7719861972',
      desc: "Are you interested in hearing from successful entrepreneurs and industry leaders about their experiences and insights? Then the Highlight Sessions are the events for you! At National Entrepreneur Summit [NES]’s Highlight Sessions, you'll have the opportunity to attend talks and panel discussions featuring successful entrepreneurs, industry experts, and thought leaders. You'll be able to learn about their journeys, ask questions, and gain valuable insights into the world of business and entrepreneurship. The Highlight Sessions are a great way to get inspired, learn from the best, and connect with other students who share your interests. So mark your calendar and don't miss out on this amazing opportunity! ",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680550464/Anmol%20Pattnayak/Posters/dummy_vco8tb.jpg',
      link: 'https://unstop.com/p/national-entrepreneurship-summit-national-e-summit-2023-nit-rourkela-659882',
    },
    {
      heading: 'Highlight Sessions 2',
      subHeading: 'e-cell',
      dateTime: '7th April, 12:00PM IST',
      location: 'NIT Rourkela',
      firstContact: 'Swarnim: 8319493047',
      secondContact: 'Harsh: 7719861972',
      desc: "Are you interested in hearing from successful entrepreneurs and industry leaders about their experiences and insights? Then the Highlight Sessions are the events for you! At National Entrepreneur Summit [NES]’s Highlight Sessions, you'll have the opportunity to attend talks and panel discussions featuring successful entrepreneurs, industry experts, and thought leaders. You'll be able to learn about their journeys, ask questions, and gain valuable insights into the world of business and entrepreneurship. The Highlight Sessions are a great way to get inspired, learn from the best, and connect with other students who share your interests. So mark your calendar and don't miss out on this amazing opportunity! ",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680550464/Anmol%20Pattnayak/Posters/dummy_vco8tb.jpg',
      link: 'https://unstop.com/p/national-entrepreneurship-summit-national-e-summit-2023-nit-rourkela-659882',
    },
    {
      heading: 'Highlight Sessions 3',
      subHeading: 'e-cell',
      dateTime: '7th April, 12:00PM IST',
      location: 'NIT Rourkela',
      firstContact: 'Swarnim: 8319493047',
      secondContact: 'Harsh: 7719861972',
      desc: "Are you interested in hearing from successful entrepreneurs and industry leaders about their experiences and insights? Then the Highlight Sessions are the events for you! At National Entrepreneur Summit [NES]’s Highlight Sessions, you'll have the opportunity to attend talks and panel discussions featuring successful entrepreneurs, industry experts, and thought leaders. You'll be able to learn about their journeys, ask questions, and gain valuable insights into the world of business and entrepreneurship. The Highlight Sessions are a great way to get inspired, learn from the best, and connect with other students who share your interests. So mark your calendar and don't miss out on this amazing opportunity! ",
      pic: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680550464/Anmol%20Pattnayak/Posters/dummy_vco8tb.jpg',
      link: 'https://unstop.com/p/national-entrepreneurship-summit-national-e-summit-2023-nit-rourkela-659882',
    },
  ],
}
