export default {
  EventDetail: [
    {
      heading: 'Shark Tank',
      subHeading: 'e-cell',
      dateTime: '8th February 2023, 8:00PM IST',
      location: 'DBA, NIT Rourkela',
      prize: 'upto 2500',
      firstContact: 'Anmol: 7683xxxxxx',
      secondContact: 'Ashutosh: 7683xxxxxx',
      desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tellus magna, finibus viverra lacinia elementum,',
      pic: 'https://picsum.photos/200',
    },
    {
      heading: 'Shark Tank',
      subHeading: 'e-cell',
      dateTime: '8th February 2023, 8:00PM IST',
      location: 'DBA, NIT Rourkela',
      prize: 'upto 2500',
      firstContact: 'Anmol: 7683xxxxxx',
      secondContact: 'Ashutosh: 7683xxxxxx',
      desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tellus magna, finibus viverra lacinia elementum,',
      pic: 'https://picsum.photos/200',
    },
    {
      heading: 'Shark Tank',
      subHeading: 'e-cell',
      dateTime: '8th February 2023, 8:00PM IST',
      location: 'DBA, NIT Rourkela',
      prize: 'upto 2500',
      firstContact: 'Anmol: 7683xxxxxx',
      secondContact: 'Ashutosh: 7683xxxxxx',
      desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tellus magna, finibus viverra lacinia elementum,',
      pic: 'https://picsum.photos/200',
    },
  ],
}
