export default{
 Investors: [
    { name: 'Astitva Tripathi', desig: 'Co-Founder Design X', desc: 'Major League Hacking (http://www.mlh.io/) is an organization built on empowering hackers. They do amazing stuff for anyone who goes to hackathons, wants to, or even plans hackathons (University and HighSchool).', pic: 'https://res.cloudinary.com/dmofs5r4h/image/upload/v1675780893/Frame_59_ozavok.png' },
    { name: 'Astitva Tripathi', desig: 'Co-Founder Design X', desc: 'Major League Hacking (http://www.mlh.io/) is an organization built on empowering hackers. They do amazing stuff for anyone who goes to hackathons, wants to, or even plans hackathons (University and HighSchool).', pic: 'https://res.cloudinary.com/dmofs5r4h/image/upload/v1675780893/Frame_59_ozavok.png' },
    { name: 'Astitva Tripathi', desig: 'Co-Founder Design X', desc: 'Major League Hacking (http://www.mlh.io/) is an organization built on empowering hackers. They do amazing stuff for anyone who goes to hackathons, wants to, or even plans hackathons (University and HighSchool).', pic: 'https://res.cloudinary.com/dmofs5r4h/image/upload/v1675780893/Frame_59_ozavok.png' },
    { name: 'Astitva Tripathi', desig: 'Co-Founder Design X', desc: 'Major League Hacking (http://www.mlh.io/) is an organization built on empowering hackers. They do amazing stuff for anyone who goes to hackathons, wants to, or even plans hackathons (University and HighSchool).', pic: 'https://res.cloudinary.com/dmofs5r4h/image/upload/v1675780893/Frame_59_ozavok.png' },
    { name: 'Anmol Pattnayak', desig: 'Co-Founder Design X', desc: 'Major League Hacking (http://www.mlh.io/) is an organization built on empowering hackers. They do amazing stuff for anyone who goes to hackathons, wants to, or even plans hackathons (University and HighSchool).', pic: 'https://res.cloudinary.com/dmofs5r4h/image/upload/v1675780893/Frame_59_ozavok.png' },
    { name: 'Astitva Tripathi', desig: 'Co-Founder Design X', desc: 'Major League Hacking (http://www.mlh.io/) is an organization built on empowering hackers. They do amazing stuff for anyone who goes to hackathons, wants to, or even plans hackathons (University and HighSchool).', pic: 'https://res.cloudinary.com/dmofs5r4h/image/upload/v1675780893/Frame_59_ozavok.png' },
    { name: 'Astitva Tripathi', desig: 'Co-Founder Design X', desc: 'Major League Hacking (http://www.mlh.io/) is an organization built on empowering hackers. They do amazing stuff for anyone who goes to hackathons, wants to, or even plans hackathons (University and HighSchool).', pic: 'https://res.cloudinary.com/dmofs5r4h/image/upload/v1675780893/Frame_59_ozavok.png' },
    { name: 'Astitva Tripathi', desig: 'Co-Founder Design X', desc: 'Major League Hacking (http://www.mlh.io/) is an organization built on empowering hackers. They do amazing stuff for anyone who goes to hackathons, wants to, or even plans hackathons (University and HighSchool).', pic: 'https://res.cloudinary.com/dmofs5r4h/image/upload/v1675780893/Frame_59_ozavok.png' },
    { name: 'Astitva Tripathi', desig: 'Co-Founder Design X', desc: 'Major League Hacking (http://www.mlh.io/) is an organization built on empowering hackers. They do amazing stuff for anyone who goes to hackathons, wants to, or even plans hackathons (University and HighSchool).', pic: 'https://res.cloudinary.com/dmofs5r4h/image/upload/v1675780893/Frame_59_ozavok.png' },
    { name: 'Astitva Tripathi', desig: 'Co-Founder Design X', desc: 'Major League Hacking (http://www.mlh.io/) is an organization built on empowering hackers. They do amazing stuff for anyone who goes to hackathons, wants to, or even plans hackathons (University and HighSchool).', pic: 'https://res.cloudinary.com/dmofs5r4h/image/upload/v1675780893/Frame_59_ozavok.png' },
  ]
}