/* eslint-disable import/no-anonymous-default-export */
/* eslint-disable max-len */

export default {
  id: 'sponsors',
  title: 'Past Sponsors',
  alpha: [
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340415/Anmol%20Pattnayak/Sponsors/128-1289753_awesome-sauce-logo-sauce_1_nbqn5v.png',
      name: 'Awesome Sauce',
      size: '100%',
      width: '200px',
      alt: 'Awesome-Sauce',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340415/Anmol%20Pattnayak/Sponsors/SIDBI_1_jmnbas.png',
      name: 'SIDBI',
      size: '90%',
      width: '190px',
      alt: 'sidbi',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340416/Anmol%20Pattnayak/Sponsors/Unitus_Seed_Fund_1_i763jy.png',
      name: 'Unitus',
      size: '90%',
      width: '250px',
      alt: 'unitus',
    },
  ],
  beta: [
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340415/Anmol%20Pattnayak/Sponsors/Mask_group_8_xnyyra.png',
      name: 'Rourkela Shines',
      size: '90%',
      width: '170px',
      alt: 'Rkl-shines',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340416/Anmol%20Pattnayak/Sponsors/Venture_Hire_1_rqbqou.png',
      name: 'Hire Ventures',
      size: '90%',
      width: '170px',
      alt: 'hire-ventures',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340415/Anmol%20Pattnayak/Sponsors/Shiva_Cement_uqru6b.png',
      name: 'Shiva Cement',
      size: '90%',
      width: '170px',
      alt: 'shiva-cement',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340415/Anmol%20Pattnayak/Sponsors/The_Education_Tree_1_uc7t8c.png',
      name: 'The Education Tree',
      size: '90%',
      width: '170px',
      alt: 'Education-Tree',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340414/Anmol%20Pattnayak/Sponsors/Campus_Bloggers_1_fqjdnn.png',
      name: 'CB',
      size: '11 0%',
      width: '170px',
      alt: 'CB',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340414/Anmol%20Pattnayak/Sponsors/1000_startups_1_lk6dxl.png',
      name: '1000',
      size: '100%',
      width: '170px',
      alt: '1000',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340414/Anmol%20Pattnayak/Sponsors/1562055335570_1_h643fk.png',
      name: 'FTBI',
      size: '100%',
      width: '170px',
      alt: 'ftbi',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340414/Anmol%20Pattnayak/Sponsors/Gupta_Powe_kcpu4c.png',
      name: 'Gupta Power',
      size: '100%',
      width: '170px',
      alt: 'Gupta Power',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340414/Anmol%20Pattnayak/Sponsors/Calcutta-Angels-Network_1_wag43z.png',
      name: 'Calcutta Angels',
      size: '90%',
      width: '170px',
      alt: 'Calcutta Angles',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340414/Anmol%20Pattnayak/Sponsors/Kotak_1_t2dyjg.png',
      name: 'Kotak',
      size: '100%',
      width: '170px',
      alt: 'Kotak',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340414/Anmol%20Pattnayak/Sponsors/Your_Story_1_zalwig.png',
      name: 'Your Story',
      size: '100%',
      width: '170px',
      alt: 'YourStory',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340414/Anmol%20Pattnayak/Sponsors/Mindfire_1_im4mhl.png',
      name: 'Mindfree',
      size: '100%',
      width: '170px',
      alt: 'mindfree',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340415/Anmol%20Pattnayak/Sponsors/Learning_while_travelling_1_yer59m.png',
      name: 'LWT',
      size: '100%',
      width: '170px',
      alt: 'lwt',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340415/Anmol%20Pattnayak/Sponsors/NSIC_1_pqgane.png',
      name: 'NSIC',
      size: '100%',
      width: '170px',
      alt: 'NSIC',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340415/Anmol%20Pattnayak/Sponsors/TIE_Global_nirrw1.jpg',
      name: 'TIE Global',
      size: '100%',
      width: '170px',
      alt: 'TIE Global',
    },
    {
      src: 'https://res.cloudinary.com/drpkgjnij/image/upload/v1680340415/Anmol%20Pattnayak/Sponsors/Startup_Odisha_wi7kbl.jpg',
      name: 'Startup Odisha',
      size: '100%',
      width: '170px',
      alt: 'startup-odisha',
    },
  ],
}
